# Generated by Django 3.2.6 on 2021-08-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakerimages',
            name='image',
            field=models.ImageField(null=True, upload_to='sneakers'),
        ),
    ]
