# Generated by Django 3.2.6 on 2021-08-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sneakerimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SneakerSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
