# Generated by Django 3.2.6 on 2021-08-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sneakersizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakersizes',
            name='sneaker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.sneaker'),
            preserve_default=False,
        ),
    ]
