# Generated by Django 3.2.6 on 2021-08-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sneakersizes_sneaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakersizes',
            old_name='size',
            new_name='size_list',
        ),
    ]
