# Generated by Django 3.2.6 on 2021-08-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_size_sneakersizes_size_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakersizes',
            old_name='size_list',
            new_name='size_number',
        ),
    ]
