# Generated by Django 3.2.6 on 2021-08-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_size_list_sneakersizes_size_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SneakerImages',
            new_name='SneakerImage',
        ),
        migrations.RenameModel(
            old_name='SneakerSizes',
            new_name='SneakerSize',
        ),
    ]
