# Generated by Django 3.2.6 on 2021-08-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_sneakerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerimage',
            name='image',
            field=models.ImageField(null=True, upload_to='sneakers/'),
        ),
    ]
