# Generated by Django 3.2.6 on 2021-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_sneakerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
