# Generated by Django 3.2.6 on 2021-09-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sneakerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakersize',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
