# Generated by Django 3.2.6 on 2021-09-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sneakersize_size_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersize',
            name='size_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
