# Generated by Django 3.2.6 on 2021-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_sneakersize_size_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakerimage',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
