# Generated by Django 3.2.6 on 2021-09-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_sneakerimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='fill_lines',
            field=models.IntegerField(default=0),
        ),
    ]
