# Generated by Django 3.2.6 on 2021-09-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sneaker_fill_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='fill_lines',
            field=models.BooleanField(default=False),
        ),
    ]
