# Generated by Django 3.2.6 on 2021-09-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_sneaker_fill_lines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='fill_lines',
            new_name='fill_line',
        ),
    ]
