# Generated by Django 3.2.6 on 2021-09-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_fill_lines_sneaker_fill_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='g_im',
            field=models.URLField(default='https://images.google.com', max_length=300),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='stockx',
            field=models.URLField(default='https://stockx.com', max_length=300),
        ),
    ]
