# Generated by Django 3.2.6 on 2021-10-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210926_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='stockx',
        ),
    ]
